/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.student;

import Model.AcademicMember;
import javax.swing.Icon;

/**
 *
 * @author HashiniAG
 */
public class Student_teacher_view extends javax.swing.JInternalFrame {
     
   int userName; 
  AcademicMember teacher=new AcademicMember();
   
    /**
     * Creates new form Student_teacher_view
     */
    public Student_teacher_view(int userName,AcademicMember teacher) {
        initComponents();
        this.userName=userName;
                          // send user name inorder to fetch the detauils of a class teacher
            // get student class room id // get teacher id 
               // return class teacher object
            
       this.teacher=teacher;
       //set window
        this.Set_Window(teacher);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T_ViewPrfile_ImageBox_panel = new javax.swing.JPanel();
        Teacher_image_Label = new javax.swing.JLabel();
        Home_Address_Label = new javax.swing.JLabel();
        Position_Label = new javax.swing.JLabel();
        Subject_Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Subject_Label1 = new javax.swing.JLabel();
        Subject_Label2 = new javax.swing.JLabel();
        Subject_Label3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Teacher_image_Label.setBackground(new java.awt.Color(255, 255, 255));
        Teacher_image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/teacher Profile.jpg"))); // NOI18N

        Home_Address_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Home_Address_Label.setText("Home Address :");

        Position_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Position_Label.setText("Position             :");

        Subject_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Subject_Label.setText("Subjects            :");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        Subject_Label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Subject_Label1.setText("Telephone   :");

        Subject_Label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Subject_Label2.setText("Mobile           :");

        Subject_Label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Subject_Label3.setText("E-mail         :");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout T_ViewPrfile_ImageBox_panelLayout = new javax.swing.GroupLayout(T_ViewPrfile_ImageBox_panel);
        T_ViewPrfile_ImageBox_panel.setLayout(T_ViewPrfile_ImageBox_panelLayout);
        T_ViewPrfile_ImageBox_panelLayout.setHorizontalGroup(
            T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Home_Address_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                    .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                        .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Subject_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Subject_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Position_Label))
                                .addGap(41, 41, 41)
                                .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Subject_Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Subject_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Teacher_image_Label)
                .addGap(54, 54, 54))
        );
        T_ViewPrfile_ImageBox_panelLayout.setVerticalGroup(
            T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Teacher_image_Label))
                    .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(Home_Address_Label))
                            .addGroup(T_ViewPrfile_ImageBox_panelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Position_Label)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Subject_Label)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Subject_Label1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Subject_Label2)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(T_ViewPrfile_ImageBox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Subject_Label3)
                            .addComponent(jLabel8))))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(T_ViewPrfile_ImageBox_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(T_ViewPrfile_ImageBox_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Set_Window(AcademicMember teacher){
    
    this.jLabel1.setText(teacher.getName());
    this.jLabel3.setText(teacher.getAddress());
    this.jLabel4.setText(teacher.getDesignation());
    this.jLabel6.setText(Integer.toString(teacher.getTelephoneNo()));
    this.jLabel7.setText(Integer.toString(teacher.getMobileNo()));
    this.jLabel8.setText(teacher.getEmail());
    this.Teacher_image_Label.setIcon((Icon) teacher.getImage());
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home_Address_Label;
    private javax.swing.JLabel Position_Label;
    private javax.swing.JLabel Subject_Label;
    private javax.swing.JLabel Subject_Label1;
    private javax.swing.JLabel Subject_Label2;
    private javax.swing.JLabel Subject_Label3;
    private javax.swing.JPanel T_ViewPrfile_ImageBox_panel;
    private javax.swing.JLabel Teacher_image_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
